"""Create table

Revision ID: c5fee816f983
Revises: 
Create Date: 2022-04-18 22:41:30.374567

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c5fee816f983"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "starlink_tracking_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_starlink_tracking_history_location",
        "starlink_tracking_history",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_starlink_tracking_history_location",
        table_name="starlink_tracking_history",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_table("starlink_tracking_history")
    # ### end Alembic commands ###
